version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: ai_chat_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: ai_chat_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - ai_chat_network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai_chat_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:admin123@mongodb:27017/ai_chat_db?authSource=admin
      - DATABASE_NAME=ai_chat_db
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - ai_chat_network

  # Next.js Web UI
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_chat_web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000/api/v1
    depends_on:
      - backend
    networks:
      - ai_chat_network

volumes:
  mongodb_data:

networks:
  ai_chat_network:
    driver: bridge 